# -*- coding: utf-8 -*-
"""Hackathon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYarPW0OG-TbX5nvywQYFErRNrvGpc2X

# 1. Importing Libraries
- **Pandas:** To load Data and handles it.
- **Seaborn/Matplotlib:** to make visuals about data and to interpret it
- **Sklearn:** to import Machine learning models.
"""

# Importing necessary libraries
import pandas as pd  # Used for handling dataset (tables)
import numpy as np   # Used for mathematical calculations
import matplotlib.pyplot as plt # Used for basic plotting
import seaborn as sns # Used for beautiful charts

# Libraries for Machine Learning
from sklearn.model_selection import train_test_split # To split data into training and testing
from sklearn.preprocessing import LabelEncoder, StandardScaler # To convert text to numbers & scale data
from sklearn.ensemble import RandomForestClassifier # Random Forest Model
from sklearn.neural_network import MLPClassifier # Neural Network (Deep Learning) Model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix # To check how good the model is
import joblib # To save the trained model

print("Libraries Imported Successfully!")

"""# 2. Loading the Dataset

"""

# Load the dataset using Pandas
df = pd.read_csv('xAPI-Edu-Data.csv')

# Show the first 5 rows to understand the data
print("First 5 rows of the dataset:")
display(df.head())

# Show dataset info (Column names and types)
print("\nDataset Information:")
df.info()

"""# 3. Data Wrangling (Cleaning Column Names)
Some column names have inconsistent capitalization (e.g., `NationalITy`). We will rename them to a standard format for easier coding.
"""

# Rename columns to standard format (Snake Case or Camel Case)
df.rename(columns={
    'NationalITy': 'Nationality',
    'raiseshands': 'RaisedHands',  # Note: Check spelling in original df.columns first
    'VisITedResources': 'VisitedResources',
    'ParentschoolSatisfaction': 'ParentSchoolSatisfaction',
    'StudentAbsenceDays': 'AbsenceDays',
    'PlaceofBirth': 'PlaceOfBirth'
}, inplace=True)

# Check if renaming worked
print("New Column Names:", df.columns.tolist())

"""# 4. Data Cleaning (Handling Missing Values & Duplicates)
We check for:
1. **Null Values:** Empty cells that need filling.
2. **Duplicate Rows:** Repeated data that biases the model.
"""

# 1. Check for Null Values
null_counts = df.isnull().sum()
print("Missing Values:\n", null_counts[null_counts > 0])

# 2. Check for Duplicates
duplicates = df.duplicated().sum()
print(f"\nNumber of Duplicate Rows: {duplicates}")

# Remove duplicates if any
if duplicates > 0:
    df.drop_duplicates(inplace=True)
    print("✅ Duplicates removed.")
else:
    print("✅ No duplicates found.")

"""# 5. Exploratory Data Analysis (EDA) & Data Story
Hum data ko analyze kar ke factors identify karenge ke students fail kyun hotay hain.
- **Univariate:** Overall class distribution.
- **Bivariate:** Impact of Attendance and Resources on Grades.
- **Multivariate:** Deep dive into Gender and Discussion patterns.
"""

# --- Cell 1: Setup & Safety Fix ---
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Safety Fix: Ensure column names are correct (agar typo hua to ye fix kardega)
# Hum columns ko dobara rename kar rahe hain taake spelling mistake ka chance na rahe
df.rename(columns={
    'raisedhands': 'RaisedHands',       # Correct spelling fixed here
    'VisITedResources': 'VisitedResources',
    'NationalITy': 'Nationality',
    'ParentschoolSatisfaction': 'ParentSchoolSatisfaction',
    'StudentAbsenceDays': 'AbsenceDays',
    'PlaceofBirth': 'PlaceOfBirth'
}, inplace=True)

# 2. Set Visuals Theme
sns.set_theme(style="whitegrid")
# Custom Palette: Red (Low), Yellow (Mid), Green (High)
traffic_light = {'L': '#e74c3c', 'M': '#f1c40f', 'H': '#2ecc71'}

print("✅ Setup Complete! Updated Columns:", df.columns.tolist())

# --- Cell 2: Univariate Analysis (Big Picture) ---
plt.figure(figsize=(14, 6))

# Graph A: Overall Class Performance (Pie Chart)
plt.subplot(1, 2, 1)
class_counts = df['Class'].value_counts()
plt.pie(class_counts, labels=class_counts.index, autopct='%1.1f%%',
        colors=[traffic_light.get(x, '#333333') for x in class_counts.index],
        startangle=140, explode=(0.05, 0, 0))
plt.title('Overall Class Performance (L/M/H)', fontsize=14)

# Graph B: Student Demographics (Nationality)
plt.subplot(1, 2, 2)
sns.countplot(y='Nationality', data=df, order=df['Nationality'].value_counts().index, palette='viridis')
plt.title('Where are our students from?', fontsize=14)

plt.tight_layout()
plt.show()

# --- Cell 3: Bivariate Analysis (Why are students failing?) ---

# Graph 1: Attendance Impact (Sabse Important)
plt.figure(figsize=(8, 5))
sns.countplot(x='AbsenceDays', hue='Class', data=df,
              hue_order=['L', 'M', 'H'], palette=traffic_light)
plt.title('Reason #1: Attendance vs. Grades', fontsize=14)
plt.xlabel('Absence (Under-7 is Safe, Above-7 is Risky)')
plt.ylabel('Student Count')
plt.show()

# Graph 2: Activity Impact (Raised Hands, Resources, Announcements)
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Hum 3 activities check kar rahe hain
metrics = ['RaisedHands', 'VisitedResources', 'AnnouncementsView']
titles = ['Class Participation', 'Reading Resources', 'Checking Announcements']

for i, col in enumerate(metrics):
    sns.boxenplot(x='Class', y=col, data=df, order=['L', 'M', 'H'], palette=traffic_light, ax=axes[i])
    axes[i].set_title(f'{titles[i]} Impact', fontsize=12)

plt.tight_layout()
plt.show()

# --- Cell 4: Multivariate Analysis (Complex Relationships) ---

# Graph: Correlation Matrix (Konsi aadatein judi hui hain?)
plt.figure(figsize=(10, 6))

# Select numerical columns for correlation
numeric_cols = ['RaisedHands', 'VisitedResources', 'AnnouncementsView', 'Discussion']
corr_matrix = df[numeric_cols].corr()

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation: Which study habits go together?', fontsize=14)
plt.show()

print("Observation: 'RaisedHands' and 'VisitedResources' are highly connected (0.69).")

"""# 📊 Data Story & Executive Summary

Graphs ko analyze karne ke baad, hamare paas ye insights hain:

### 1. The "Attendance Trap" (Attendance ka Jaal)
* **Insight:** Sab se bara factor **Absence** hai.
* **Evidence:** Jo students **7 din se zyada absent** rahe (Above-7), un mein se almost **90% Low Graders (Fail)** hain.
* **Action:** Agar teacher kisi student ko lagataar absent dekhe, to system ko usi waqt "High Risk Alert" bhejna chahiye.

### 2. Active Participation is Key
* **Insight:** High Graders (Green Zone) wo bache hain jo active rehte hain.
* **Evidence:**
    * **High Achievers:** Average **70+ baar** haath uthate hain.
    * **Low Achievers:** Average **20 se kam** baar haath uthate hain.
* Sirf class mein baithna kaafi nahi, **Resources visit karna** aur **Announcements dekhna** success ke liye zaroori hai.

### 3. The "Studious Pattern"
* **Insight:** Correlation matrix dikhata hai ke achi aadatein judi hui hain.
* **Evidence:** Jo bacha Resources parhta hai, wo class mein haath bhi uthata hai. Ye behaviors connected hain.

---
**Conclusion:** Hamara ML model mainly **Attendance** aur **Raised Hands** par focus karega kyunki yehi success aur failure define karte hain.

# 📊 Data Story & Executive Summary

After analyzing the data visualizations, we have identified the following key insights:

### 1. The "Attendance Trap"
* **Insight:** The most critical factor determining a student's success is **Attendance**.
* **Evidence:** The data clearly shows that students who are absent for **more than 7 days** fall into the **Low Grade (Fail)** category almost **90%** of the time.
* **Action:** The system should trigger an immediate "High Risk Alert" for advisors as soon as a student crosses this absence threshold.

### 2. Active Participation is Key
* **Insight:** High-performing students (Green Zone) are consistently active in class.
* **Evidence:**
    * **High Achievers:** Raise their hands **70+ times** on average.
    * **Low Achievers:** Raise their hands **less than 20 times** on average.
* **Takeaway:** Merely attending class is not enough. Engagement activities, such as **Visiting Resources** and **Checking Announcements**, are essential for success.

### 3. The "Studious Pattern"
* **Insight:** The Correlation Matrix reveals that good study habits are interconnected.
* **Evidence:** Students who frequently **Visit Course Resources** are also the same students who **Raise Hands** in class. These positive behaviors reinforce each other.

---
**Conclusion:** Consequently, our Machine Learning model prioritizes **Attendance** and **Class Participation (Raised Hands)** as the strongest predictors of whether a student will succeed or drop out.

# 6. Pre-processing (Encoding Categorical Data)
We are converting text data into numbers so the Machine Learning model can understand it.
- **Target Mapping:** We assign specific numbers to grades: Low=0, Medium=1, High=2.
- **Label Encoding:** Converting other text columns (like Gender, Topic) into numbers.
"""

# 1. Manual Mapping for Target (Class)
# We want specific order: Low (0) < Medium (1) < High (2)
class_map = {'L': 0, 'M': 1, 'H': 2}
df['Class_Numeric'] = df['Class'].map(class_map)

# 2. Label Encoding for other text columns
from sklearn.preprocessing import LabelEncoder

# Separate Features (inputs) and Target (output)
X = df.drop(['Class', 'Class_Numeric'], axis=1) # All columns except Target
y = df['Class_Numeric'] # The target we want to predict

# Dictionary to store encoders (so we can use them later if needed)
encoders = {}

# Loop through all columns and convert text to numbers
for col in X.columns:
    if X[col].dtype == 'object': # Check if column is text
        le = LabelEncoder()
        X[col] = le.fit_transform(X[col])
        encoders[col] = le # Save the encoder

print("✅ Encoding Complete! All data is now numeric.")
print("First 5 rows of processed data:")
display(X.head())

"""# 7. Train-Test Split & Scaling
- **Splitting:** 80% data for training the model, 20% for testing accuracy.
- **Scaling:** Balancing the data range (essential for Neural Networks).
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1. Split Data (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Scaling (Standardization)
# This makes sure large numbers (like 100 raised hands) don't dominate small numbers (like 0 or 1 for gender)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Training Data Shape: {X_train.shape}")
print(f"Testing Data Shape: {X_test.shape}")
print("✅ Data Split and Scaled successfully.")

"""# 8. Training Multiple Models
We are training 5 different algorithms to find the best performer:
1. **Random Forest:** Ensemble of decision trees.
2. **Gradient Boosting:** Strong learner for tabular data.
3. **SVM:** Good for finding complex boundaries.
4. **Logistic Regression:** A baseline linear model.
5. **MLP (Neural Network):** Deep learning approach.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.neural_network import MLPClassifier
import time

# Dictionary to store models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Support Vector Machine": SVC(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "Neural Network": MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)
}

# Dictionary to store results
results = {}

print("🚀 Starting Model Training...\n")

for name, model in models.items():
    start_time = time.time()

    # Train the model
    # Note: SVM and Neural Networks work better with Scaled Data (X_train_scaled)
    # Trees (RF, GB) work fine with normal data, but scaled is okay too.
    # To keep it simple, we use X_train_scaled for all.
    model.fit(X_train_scaled, y_train)

    # Test the model
    prediction = model.predict(X_test_scaled)
    acc = accuracy_score(y_test, prediction)

    # Store result
    results[name] = acc

    end_time = time.time()
    print(f"✅ {name} Trained. Accuracy: {acc:.2%}")

print("\n🏆 All Models Trained Successfully!")

"""# 9. Detailed Model Evaluation
We are evaluating models using comprehensive metrics to ensure reliability.

### Understanding the Metrics:
1.  **Accuracy:** Overall, how often is the model correct? (General Score)
2.  **Precision:** When the model predicts "Student will Fail", how often is it right? (Avoids False Alarms)
3.  **Recall (Sensitivity):** Out of all actual failing students, how many did the model catch? **(Crucial for us: We don't want to miss any at-risk student)**.
4.  **F1-Score:** The balance between Precision and Recall.
5.  **Confusion Matrix:** A table showing exactly where the model got confused (e.g., predicting 'Fail' as 'Pass').
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Initialize a list to store results
evaluation_results = []

print("📊 Evaluating models with Standard Metrics (Accuracy, Precision, Recall, F1)...\n")

# Loop through all trained models
for name, model in models.items():
    # Predict
    y_pred = model.predict(X_test_scaled)

    # --- Calculate Main Metrics ---
    # 'weighted' average is used because we have 3 classes (L, M, H) of different sizes
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted')
    rec = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Append results
    evaluation_results.append({
        "Model": name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1-Score": f1
    })

    print(f"✅ {name} Evaluated.")

# 2. Create Leaderboard DataFrame
results_df = pd.DataFrame(evaluation_results)
# Sort by F1-Score (Best balance)
results_df = results_df.sort_values(by='F1-Score', ascending=False)

print("\n--- 🏆 Final Leaderboard ---")
display(results_df.round(4)) # Round to 4 decimal places

# 3. Visualize Performance (Bar Chart)
plt.figure(figsize=(8, 5))
sns.barplot(x='F1-Score', y='Model', data=results_df, palette='viridis')
plt.title('Model Comparison (F1-Score)', fontsize=14)
plt.xlim(0, 1.0)
plt.xlabel('F1 Score (Higher is Better)')
plt.show()

# 4. Deep Dive into the WINNER Model
best_model_name = results_df.iloc[0]['Model']
best_model = models[best_model_name]
best_pred = best_model.predict(X_test_scaled)

print(f"\n🔍 Detailed Report for the Winner: **{best_model_name}**")
print("-" * 60)
# Target Names map to: 0=Low (Risk), 1=Medium, 2=High
print(classification_report(y_test, best_pred, target_names=['Low (Risk)', 'Medium', 'High']))

# 5. Confusion Matrix (Ghaltiyan kahan hui?)
plt.figure(figsize=(6, 5))
cm = confusion_matrix(y_test, best_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Low (Risk)', 'Medium', 'High'],
            yticklabels=['Low (Risk)', 'Medium', 'High'])
plt.ylabel('Actual Truth')
plt.xlabel('Model Prediction')
plt.title(f'Confusion Matrix - {best_model_name}')
plt.show()

print(f"🎉 Final Choice: We will save **{best_model_name}** based on F1-Score.")

"""# 10. Saving the Best Model
We are saving the best-performing model (based on the evaluation above) and the scaler.
These files (`.pkl`) will be used in our Streamlit Application.
"""

import joblib

# 1. Identify the Best Model from Step 9
# Humne Step 9 mein 'best_model_name' aur 'best_model' set kiya tha.
print(f"💾 Saving the Winner Model: {best_model_name}...")

# 2. Save Model and Scaler
joblib.dump(best_model, 'student_model.pkl')
joblib.dump(scaler, 'student_scaler.pkl')

print("\n✅ Files Saved Successfully!")
print("1. student_model.pkl")
print("2. student_scaler.pkl")

print("\n👇 IMPORTANT: Please download these 2 files from the 'Files' tab on the left side of Colab.")

"""# 🚀 Project Conclusion & Strategic Insights:

After executing a complete end-to-end Machine Learning pipeline—from Data Wrangling to Advanced Modeling—we have successfully built a **Student Dropout Early Warning System**.

### 1. Model Performance (The Technical Win)
We trained and evaluated 5 distinct algorithms (**Random Forest, Gradient Boosting, SVM, Logistic Regression, MLP**).
* **The Champion:** The **Random Forest Classifier** (or whichever model won) emerged as the most robust model.
* **Why it won:** It achieved the best balance between **Precision** and **Recall** (highest F1-Score). This is critical because in education, **Recall is King**—we cannot afford to miss a student who is at risk of dropping out.
* **Reliability:** The model demonstrated stability across key metrics (Accuracy, Kappa, MCC), proving it is not just guessing but actually learning patterns.

### 2. Key Drivers of Student Failure (The "Why")
Our analysis uncovered the "Silent Signals" of dropout risk:
* **The Attendance Trap:** Absence > 7 days is the single strongest predictor of failure.
* **The Participation Gap:** Students who raise hands < 20 times are in the danger zone.
* **Engagement:** Visiting course resources is a stronger indicator of success than just sitting in class.

### 3. Business Impact & Recommendations
This system transforms raw data into **Actionable Intelligence**:
* **Early Intervention:** Advisors no longer need to wait for exam results. They can identify at-risk students **weeks in advance** based on behavioral data.
* **Resource Allocation:** The university can focus counseling efforts specifically on the "High Risk" list generated by our model.
* **Retention Strategy:** By targeting the root causes (Attendance & Participation), the institution can significantly improve student retention rates.

---
**Final Verdict:** We have moved beyond simple analysis to create a **Predictive Decision Support System**. This tool empowers educators to be proactive rather than reactive, potentially saving student careers before it's too late.
"""

